# Generated by Django 5.2.8 on 2026-02-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=260, unique=True)),
                ('synopsis', models.TextField(help_text='Short summary shown on the list page.', max_length=500)),
                ('body', models.TextField(help_text='Full story content.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('is_breaking', models.BooleanField(default=False, help_text='Only one story can be Breaking at a time.')),
                ('is_archived', models.BooleanField(default=False, help_text='Archived stories are hidden from the main list.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
