"""
Django settings for iota project.

Generated by 'django-admin startproject' using Django 6.0.

Documentation:
https://docs.djangoproject.com/en/6.0/topics/settings/
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Load env vars (SECRET_KEY, DB settings, etc.)
if os.path.exists("env.py"):
    import env  # noqa

# Build paths
BASE_DIR = Path(__file__).resolve().parent.parent


# -----------------------------------------------------------
# BASIC SETTINGS
# -----------------------------------------------------------
SECRET_KEY = os.environ.get("SECRET_KEY")
DEBUG = os.environ.get("DEVELOPMENT", "False") == "True"
ALLOWED_HOSTS = ["127.0.0.1"]


# -----------------------------------------------------------
# APPLICATIONS
# -----------------------------------------------------------

INSTALLED_APPS = [
    # Django defaults
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",

    # Allauth
    "allauth",
    "allauth.account",
    "allauth.socialaccount",

    # apps
    "home",
    "academy",
    "news",
    "shop",

    # third-party
    "django_ckeditor_5",
]

SITE_ID = 1


# -----------------------------------------------------------
# MIDDLEWARE
# -----------------------------------------------------------

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",

    # REQUIRED for Django 6 + Allauth
    "allauth.account.middleware.AccountMiddleware",

    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# -----------------------------------------------------------
# AUTHENTICATION BACKENDS
# -----------------------------------------------------------

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]


# -----------------------------------------------------------
# ALLAUTH CONFIGURATION
# -----------------------------------------------------------

LOGIN_REDIRECT_URL = "/"
ACCOUNT_LOGOUT_REDIRECT_URL = "/"

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "none"  # Use "mandatory" in production
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = "username_email"


# -----------------------------------------------------------
# TEMPLATES
# -----------------------------------------------------------

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


ROOT_URLCONF = "iota.urls"
WSGI_APPLICATION = "iota.wsgi.application"


# -----------------------------------------------------------
# DATABASE
# -----------------------------------------------------------

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# -----------------------------------------------------------
# PASSWORD VALIDATION
# -----------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# -----------------------------------------------------------
# INTERNATIONALIZATION
# -----------------------------------------------------------

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# -----------------------------------------------------------
# STATIC & MEDIA FILES
# -----------------------------------------------------------

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# CKEditor 5 (django-ckeditor-5)
CKEDITOR_5_FILE_UPLOAD_PERMISSION = "staff"

# CKEditor 5 (django-ckeditor-5)
CKEDITOR_5_FILE_UPLOAD_PERMISSION = "staff"

CKEDITOR_5_CONFIGS = {
    "default": {
        "toolbar": {
            "items": [
                "heading", "|",
                "bold", "italic", "link", "|",
                "bulletedList", "numberedList", "|",
                "blockQuote", "undo", "redo",
            ],
            "shouldNotGroupWhenFull": True,
        },
    },

    "extends": {
        "toolbar": {
            "items": [
                # Structure
                "heading", "|",

                # Core formatting
                "bold", "italic", "underline", "strikethrough", "subscript", "superscript", "|",

                # Typography
                "fontSize", "fontFamily",
                "fontColor", "fontBackgroundColor", "|",

                # Alignment / layout
                "alignment", "|",

                # Links + media
                "link", "mediaEmbed", "|",

                # Lists + indentation
                "bulletedList", "numberedList", "todoList", "|",
                "outdent", "indent", "|",

                # Inserts
                "insertTable", "horizontalLine", "specialCharacters", "|",

                # Blocks
                "blockQuote", "code", "codeBlock", "|",

                # Editing tools
                "removeFormat", "findAndReplace", "|",
                "undo", "redo", "|",

                # Power tools
                "sourceEditing",
            ],
            "shouldNotGroupWhenFull": True,
        },

        # Optional but useful for content teams
        "table": {
            "contentToolbar": [
                "tableColumn", "tableRow", "mergeTableCells",
                "tableProperties", "tableCellProperties",
            ]
        },

        "heading": {
            "options": [
                {"model": "paragraph", "title": "Paragraph", "class": "ck-heading_paragraph"},
                {"model": "heading1", "view": "h2", "title": "Heading", "class": "ck-heading_heading1"},
                {"model": "heading2", "view": "h3", "title": "Subheading", "class": "ck-heading_heading2"},
                {"model": "heading3", "view": "h4", "title": "Section title", "class": "ck-heading_heading3"},
            ]
        },
    },
}

# -----------------------------------------------------------
# DEFAULT PRIMARY KEY
# -----------------------------------------------------------

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# -----------------------------------------------------------
# EMAIL (DEV MODE)
# -----------------------------------------------------------

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
